config/routes.rb
Rails.application.routes.draw do
  # get 'questions/index'
  # get 'questions/show'
  # get 'questions/new'
  # get 'questions/edit'
  root 'questions#index'

  resources :questions

  get 'snippets/app'
  resources :snippets

  get 'hello/index'
  get 'hello', to: 'hello#index'
  get 'hello/other'

  post 'hello/index'
  post 'hello', to: 'hello#index'
  post 'hello/other'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  validates :name, presence: true
  validates :title, presence: true
  validates :content, presence: true
end

app/models/snippet.rb
class Snippet < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	# Prevent CSRF attacks by raising an exception.
	# For APIs, you may want to use :null_session instead.
	# ===== for Post Data width Axios =====
	protect_from_forgery with: :null_session
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  #protect_from_forgery

  def index

    if params['msg'] != nil then
      @msg = '来たね、 ' + params['msg'] + '！'
    else
      @msg = 'This is Default Title'
    end

    if request.post? then
      @title = "Result"
      @msg = 'You type:' + params['input1']
      @value = params['input1']
    else
      @title = "Title"
      @msg = "Type Here..."
      @value = ''

      # for CheckBox
      # if params['input1']
      #     @message = 'You Checked-1!'
    #   else
    #     @message = 'Not Checked!'
    #   # @message = 'You typed:' + params['input1']
    #   # @value = params['input1']
    #   end
    # else
    #   @title = 'Index Page'
    #   @message = 'Check it...!'
    #   # @value = ''
    end

  end

  def other
    redirect_to action: :index, params: {'msg': 'Come to Other Page'}
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end

  def show
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      redirect_to root_path, notice: 'Success!'
    else
      flash[:alert] = 'Save error'
      render :new
    end
  end

  def edit
  end

  private
    def question_params
      # byebug <- degug => param
      params.require(:question).permit(:name, :title, :content)
    end

end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
  before_action :set_snippet, only: %i[ show edit update destroy ]

  # GET /snippets or /snippets.json
  def index
    @snippets = Snippet.all
  end

  # GET /snippets/1 or /snippets/1.json
  def show
  end

  # GET /snippets/new
  def new
    @snippet = Snippet.new
  end

  # GET /snippets/1/edit
  def edit
  end

  # POST /snippets or /snippets.json
  def create
    @snippet = Snippet.new(snippet_params)

    respond_to do |format|
      if @snippet.save
        format.html { redirect_to @snippet, notice: "Snippet was successfully created." }
        format.json { render :show, status: :created, location: @snippet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @snippet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /snippets/1 or /snippets/1.json
  def update
    respond_to do |format|
      if @snippet.update(snippet_params)
        format.html { redirect_to @snippet, notice: "Snippet was successfully updated." }
        format.json { render :show, status: :ok, location: @snippet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @snippet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /snippets/1 or /snippets/1.json
  def destroy
    @snippet.destroy
    respond_to do |format|
      format.html { redirect_to snippets_url, notice: "Snippet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_snippet
      @snippet = Snippet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def snippet_params
      params.require(:snippet).permit(:title, :language, :contents)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/snippets_helper.rb
module SnippetsHelper
end

app/views/hello/index.html.erb
<div class="container">
  <div class="row mt-4">
    <%# <h1>Hello React</h1> %>

    <h2 class="display-2">Hello <%= @title %></h2>
    <%
=begin%>
    <h3 class="display-3"><% @message %></h3>
    <%
=end%>

    <%# Default form with: protect_from_forgery on hello_controller for Security %>
    <h3 class="display-3"><%= @msg %></h3>
    <form method="POST" action="/hello/index">
      <input type="text" name="input1" value="<%= @value %>" class="form-control m-3">
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>

    <%# <form method="POST" action="/hello" > %>
    <%# <input type="text" name="input1" value="<%= @value %>
    <%# <input type="submit" > %>
    <%# </form> %>


    <% form_tag(controller: "hello", action: "index") do %>
    <%= text_field_tag("input1") %>
    <%= submit_tag("送信する") %>
    <% end %>


    <%
=begin%>
    // form-helper input-text
    <%= form_tag(controller: "hello", action: "index") do %>
    <%= text_field_tag("input1", "", {class: "form-control"}) %>
    <%= submit_tag("送信する", {class: "btn btn-primary"}) %>
    <%
=end%>


    <%# <%= javascript_pack_tag 'hello_react' %>
    <%#= react_component("HelloWorld", { greeting: "Hello from react-rails.", result: "Dummy Result"}) %>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>RailsReactApp</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%# <%= stylesheet_pack_tag 'hello_vue' %>

  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%# <%= javascript_pack_tag 'hello_vue' %>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
</head>

<body class="wrapper">

  <%= yield %>
</body>

</html>

app/views/questions/edit.html.erb
<h1>Questions#edit</h1>
<p>Find me in app/views/questions/edit.html.erb</p>

app/views/questions/index.html.erb
<h1 class="display-1 my-4">QA Service</h1>

<div class="container">
  <div class="row">
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Title</th>
          <th scope="col">Menu</th>
          <th scope="col">Content</th>
        </tr>
      </thead>
      <tbody>
        <% @questions.each do |question| %>
        <tr>
          <th scope="row"><%= question.id %></th>
          <td><%= question.title %></td>
          <td><%= question.content %></td>
          <td>[Edit] [Delete]</td>
        </tr>
        <% end %>
      </tbody>
    </table>

    <div class="">
      <%= link_to 'New question', new_question_path %>
    </div>

  </div>
</div>

<%# Example %>
<%# <div class="container">
  <div class="jumbotron m-3">
    <h1 class="display-4">Hello, Bootstrap!</h1>
    <hr class="my-4">
    <p>This is the template of Ruby on Rails using Bootstrap.</p>
    <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#exampleModal">
      <i class="far fa-window-maximize"></i>
      Click here
    </button>
  </div>
  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          Hello!
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
</div> %>

app/views/questions/new.html.erb
<h1 class="display-1 my-4">QA Service / New</h1>

<div class="container">
	<div class="row">

		<div class="col-md-4 offset-md-4">

			<% if flash[:notice] %>
			<p class="text-success text-center"><%= flash[:notice] %></p>
			<% else flash[:alert] %>
			<p class="text-danger text-center"><%= flash[:alert] %></p>
			<% end %>

			<%= form_with model: @question, local: true do |f| %>
			<div class="form-group">
				<label for="name">Name</label>
				<%= f.text_field :name, class: 'form-control', id: "name", placeholder: "Please input name" %>
			</div>

			<div class="form-group">
				<label for="title">Title</label>
				<%= f.text_field :title, class: 'form-control', id: "title", placeholder: "Please input title" %>
			</div>

			<div class="form-group">
				<label for="content">Content</label>
				<%= f.text_area :content, class: 'form-control', id: "content", placeholder: "Please input title" %>
			</div>

			<div class="text-center">
				<%= f.submit "Save", class: 'btn btn-primary' %>
			</div>
			<% end %>

			<div class="">
				<%# <%= link_to 'Index question', root_path %>
				<%= link_to 'Index question', questions_path %>
			</div>

		</div>
	</div>
</div>

app/views/questions/show.html.erb
<h1>Questions#show</h1>
<p>Find me in app/views/questions/show.html.erb</p>

app/views/snippets/_form.html.erb
<%= form_with(model: snippet) do |form| %>
  <% if snippet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(snippet.errors.count, "error") %> prohibited this snippet from being saved:</h2>

      <ul>
        <% snippet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :language %>
    <%= form.text_field :language %>
  </div>

  <div class="field">
    <%= form.label :contents %>
    <%= form.text_field :contents %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/snippets/app.html.erb
<%= javascript_pack_tag 'hello_vue' %>

app/views/snippets/edit.html.erb
<h1>Editing Snippet</h1>

<%= render 'form', snippet: @snippet %>

<%= link_to 'Show', @snippet %> |
<%= link_to 'Back', snippets_path %>

app/views/snippets/index.html.erb
<div class="container my-4">
  <p id="notice"><%= notice %></p>

  <h1>Snippets</h1>

  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Language</th>
        <th>Contents</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @snippets.each do |snippet| %>
      <tr>
        <td><%= snippet.title %></td>
        <td><%= snippet.language %></td>
        <td><%= snippet.contents %></td>
        <td><%= link_to 'Show', snippet %></td>
        <td><%= link_to 'Edit', edit_snippet_path(snippet) %></td>
        <td><%= link_to 'Destroy', snippet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Snippet', new_snippet_path %>
</div>

app/views/snippets/new.html.erb
<h1>New Snippet</h1>

<%= render 'form', snippet: @snippet %>

<%= link_to 'Back', snippets_path %>

app/views/snippets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @snippet.title %>
</p>

<p>
  <strong>Language:</strong>
  <%= @snippet.language %>
</p>

<p>
  <strong>Contents:</strong>
  <%= @snippet.contents %>
</p>

<%= link_to 'Edit', edit_snippet_path(@snippet) %> |
<%= link_to 'Back', snippets_path %>